---
title: "トキの分布をしらべる"
author: "伊東宏樹"
date: 2026-05-30
lang: ja
format:
  revealjs:
    theme: [default, custom.scss]
    code-copy: true
embed-resources: true
slide-number: true
---

## はじめに

トキ放鳥

## GBIF

GBIF

## 種のデータ取得

トキの学名Nipponia nipponを指定してGBIFから種のデータを取得

```{r}
#| label: setup

library(tidyverse)
library(rgbif)

species_data <- name_backbone("Nipponia nippon")
print(species_data)
```

## データを取得

usageKeyを指定して、Occurrenceデータのダウンロード情報を取得

```{r}
#| label: occ_download

taxon_key <- species_data$usageKey
occ_info <- occ_download(pred("taxonKey", taxon_key),
                         pred("hasCoordinate", TRUE))
(meta <- occ_download_meta(occ_info))
```

occ_download_wait()で準備を待つ

occ_download_get()でデータを取得

ダウンロードしたデータを読み込み

```{r}
occ_download_wait(occ_info)
x <- occ_download_get(occ_info)
df <- occ_download_import(x)
```

## 国別

```{r}
df |>
  pull(countryCode) |>
  table()
```

```{r}
df_jp <- df |>
  dplyr::filter(countryCode == "JP")
  
df_jp |>
  pull(stateProvince) |>
  table()
```

## 地図表示

leaflet

```{r}
library(leaflet)

map <- leaflet() |>
  addTiles() |>
  setView(lng = 125, lat = 35, zoom = 4) |>
  addCircleMarkers(lng = df$decimalLongitude,
                   lat = df$decimalLatitude,
                   color = "red",
                   radius = 3)
```

view

```{r}
map
```
